// Generated by TKG at 2017-05-19 17:25:36

#include "keymap_common.h"

#define KEYMAP_TKG( \
    K0A, K0B, K0C, K0D, K0E, K0F, K0G, K0H, K0I, K0J, K0K, K0L, \
    K1A, K1B, K1C, K1D, K1E, K1F, K1G, K1H, K1I, K1J,      K1L, \
    K2A,      K2C, K2D, K2E, K2F, K2G, K2H, K2I, K2J, K2K, K2L, \
    K3A, K3B, K3C,      K3E, K3F,                K3J, K3K, K3L  \
) { \
    { KC_##K0A, KC_##K0B, KC_##K0C, KC_##K0D, KC_##K0E, KC_##K0F, KC_##K0G, KC_##K0H, KC_##K0I, KC_##K0J, KC_##K0K, KC_##K0L }, \
    { KC_##K1A, KC_##K1B, KC_##K1C, KC_##K1D, KC_##K1E, KC_##K1F, KC_##K1G, KC_##K1H, KC_##K1I, KC_##K1J, KC_NO,    KC_##K1L }, \
    { KC_##K2A, KC_NO,    KC_##K2C, KC_##K2D, KC_##K2E, KC_##K2F, KC_##K2G, KC_##K2H, KC_##K2I, KC_##K2J, KC_##K2K, KC_##K2L }, \
    { KC_##K3A, KC_##K3B, KC_##K3C, KC_NO,    KC_##K3E, KC_##K3F, KC_NO,    KC_NO,    KC_NO,    KC_##K3J, KC_##K3K, KC_##K3L }  \
}

#ifdef KEYMAP_SECTION_ENABLE
const uint8_t keymaps[][MATRIX_ROWS][MATRIX_COLS] __attribute__ ((section (".keymap.keymaps"))) = {
#else
const uint8_t keymaps[][MATRIX_ROWS][MATRIX_COLS] PROGMEM = {
#endif
    [0] = KEYMAP_TKG(
        ESC, Q,   W,   E,   R,   T,   Y,   U,   I,   O,   P,   BSPC, \
        TAB, A,   S,   D,   F,   G,   H,   J,   K,   L,        ENT,  \
        LSFT,     Z,   X,   C,   V,   B,   N,   M,   COMM,DOT, UP,   \
        LCTL,LGUI,LALT,     SPC, FN0,                LEFT,DOWN,RGHT),
    [1] = KEYMAP_TKG(
        ESC, 1,   2,   3,   4,   5,   6,   7,   8,   9,   0    MINS, \
        CAPS,F1,  F2,  F3,  INS, HOME,PGUP,LBRC,RBRC,EQL,      ENT,  \
        LSFT,     F4,  F5,  F6,  DEL, END, PGDN,SCLN,QUOT,BSLS,SLSH, \
        FN1, LGUI,LALT,     SPC, FN0,                MUTE,VOLD,VOLU),
    [2] = KEYMAP_TKG(
        GRV, TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,BSPC, \
        F7,  F8,  F9,  TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,     PSCR, \
        TRNS,     F10, F11, F12, DEL, END, PGDN,SCLN,QUOT,SLSH,FN5,  \
        FN1, LGUI,LALT,     FN8, FN0,                FN2, FN3, FN4),

};

#ifdef KEYMAP_SECTION_ENABLE
const uint16_t fn_actions[] __attribute__ ((section (".keymap.fn_actions"))) = {
#else
const uint16_t fn_actions[] PROGMEM = {
#endif
    [0] = ACTION_LAYER_MOMENTARY(1),
    [1] = ACTION_LAYER_ON(2, ON_RELEASE),
    [2] = ACTION_BACKLIGHT_TOGGLE(),
    [3] = ACTION_BACKLIGHT_DECREASE(),
    [4] = ACTION_BACKLIGHT_STEP(),
    [5] = ACTION_BACKLIGHT_INCREASE(),
    [8] = ACTION_LAYER_CLEAR(ON_RELEASE),
};